# Generated by Django 4.2.3 on 2025-07-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_question_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='grade_point',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='Sample Question', max_length=500),
            preserve_default=False,
        ),
    ]
